version: '3'
services:
    express-app:
        build: .
        ports:
            - '3000:3000'
        # We can override any env values here.
        # By default the .env in the project root will be loaded as the environment for all containers
        environment:
            APP_DEBUG: "true"
            APP_SECRET: "my name is NEO"
       
